import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ThemeContextProvider from "@/context/ThemeContext";

const popps = Poppins({
  subsets: ["devanagari"],
  weight: ["100", "200", "400", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <ThemeContextProvider>
        <body className={popps.className}>{children}</body>
      </ThemeContextProvider>
    </html>
  );
}
