import "./globals.css";
import type { Metadata } from "next";
import ThemeContextProvider from "@/context/ThemeContext";
import ThemeOverlay from "@/components/ThemeOverlay";

export const metadata: Metadata = {
  title: "Pages BookClub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body>
          <ThemeOverlay>{children}</ThemeOverlay>
        </body>
      </ThemeContextProvider>
    </html>
  );
}
